spring.application.name=restaurant_management_reservation


# ========== Server ==========
server.port=8084

# ========== Database ==========
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_management_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sohail123#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA ==========
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========== Logging for debugging ==========
logging.level.org.springframework.security=DEBUG
