spring.application.name=restaurant_management_system

# ===============================
# =  Server Configuration
# ===============================
server.port=${PORT:8081}

# ===============================
# =  Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-spring-meadow-aqhqwbn4-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZSsCTtn9qE3O
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# =  JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# =  Security & JWT Configuration
# ===============================
jwt.secret=8Tg7oYlQJ9dLkF5zXa+M2pR6vN1bBq0YgWvDsTxPjMk=
jwt.expiration=3600000
jwt.refreshExpirationInMs = 86400000


# Allow requests from frontend (Vite running on port 5173)
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=Content-Type,Authorization

