spring.application.name=restaurant_management_menu

# ========== Server ==========
server.port=${PORT:8082}

# ===============================
# =  Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-spring-meadow-aqhqwbn4-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZSsCTtn9qE3O
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== JWT Secret & Expiry ==========
jwt.secret=8Tg7oYlQJ9dLkF5zXa+M2pR6vN1bBq0YgWvDsTxPjMk=
jwt.expiration=3600000
jwt.refreshExpirationInMs=86400000

# ========== Logging for debugging ==========
logging.level.org.springframework.security=DEBUG
